KS0073SPIDriver: src/ks0073_lcd_drv.c File Reference
ks0073_lcd_drv.c File Reference
Software for a 20x4 LCD connected via SPI.
#include "ks0073_lcd_drv.h"
Functions
void DataConvert (uint8_t Data, KS0073_RWTypeDef RW, KS0073_RSTypeDef RS, KS0073_DataTypeDef *buffer)
Builds a KS0073_DataTypeDef from Data, RW & RS.
uint8_t readData ()
void setDDAddress (uint8_t DDAddress)
uint8_t readBusyFlag ()
void KS0073_Init (KS0073_CursorTypeDef Cursor, KS0073_BlinkTypeDef Blink)
Init routine of KS0073 Controller, accessed over SPI SPI init, init of GPIO for backlight & chip select.
void KS0073_DeInit ()
DeInitializes SPI and resets GPIO pins.
void KS0073_Transmit_Byte (uint8_t Data, KS0073_RWTypeDef RW, KS0073_RSTypeDef RS, uint32_t Timeout)
converts a byte to fitting format and transmits it to display
void KS0073_clearScreen ()
void KS0073_gotoxy (uint8_t posx, uint8_t posy)
void KS0073_newLine ()
void KS0073_putc (char newchar)
void KS0073_puts (char *nextchar)
uint8_t KS0073_readAddress ()
void KS0073_BL_Enable ()
void KS0073_BL_Disable ()
Disables Backlight.
void KS0073_SPI_Enable ()
void KS0073_SPI_Disable ()
void HAL_SPI_MspInit (SPI_HandleTypeDef *hspi)
SPI MSP Init SPI LowLevel Init of all Pin Out/InPuts & Clocks.
void HAL_SPI_MspDeInit (SPI_HandleTypeDef *hspi)
SPI MSP DeInit SPI LowLevel DeInit of all Pin Out/InPuts & Clocks.
Detailed Description
Software for a 20x4 LCD connected via SPI.
Author
Oliver Westermann
Version
V1.0
Date
04.05.2015
Definition in file ks0073_lcd_drv.c.
Function Documentation
void DataConvert (uint8_t Data, KS0073_RWTypeDef RW, KS0073_RSTypeDef RS, KS0073_DataTypeDef * buffer)
Builds a KS0073_DataTypeDef from Data, RW & RS.
Parameters
Data - Input Data, for example a command or a char
RW - R/W Bit, 1 for Read-Operations, 0 for Write-Operations
RS - Register Select
buffer - Pointer to a KS0073_DataTypeDef Element to save the Result
Definition at line 290 of file ks0073_lcd_drv.c.
Referenced by KS0073_Transmit_Byte().
uint8_t readBusyFlag ()
Checks BusyFlag
Returns
BusyFlag - 1 = Busy, 0 = NotBusy
Definition at line 333 of file ks0073_lcd_drv.c.
References KS0073_readAddress().
uint8_t readData ()
reads data from present address
Returns
data
Definition at line 310 of file ks0073_lcd_drv.c.
void setDDAddress (uint8_t DDAddress)
sets Address to DDAdress in DisplayRAM
Parameters
DDAddress
Definition at line 323 of file ks0073_lcd_drv.c.
References KS0073_Transmit_Byte().
Referenced by KS0073_gotoxy().